---
- name: Cau hinh tren router
  hosts: 10.215.26.180 
  gather_facts: no

  tasks:
    - name: Show vlan
      ios_command:
        commands:
          - show vlan
      register: output

    - debug: var=output.stdout_lines
